laviva_main_admin_user:
    resource: "@LavivaMainBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user/

laviva_main_homepage:
    path:     /admin
    defaults: { _controller: LavivaMainBundle:Default:index }
