laviva_back_office_product:
    resource: "@LavivaBackOfficeBundle/Controller/productController.php"
    type:     annotation

laviva_back_office_product:
    resource: "@LavivaBackOfficeBundle/Controller/productController.php"
    type:     annotation

laviva_cms:
    resource: "@LavivaCmsBundle/Resources/config/routing.yml"
    prefix:   /

laviva_front_office:
    resource: "@LavivaFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

laviva_back_office:
    resource: "@LavivaBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

laviva_main:
    resource: "@LavivaMainBundle/Resources/config/routing.yml"
    prefix:   /